app/build.gradle
app/codequality.gradle
app/config/checkstyle.xml
app/config/xsl/checkstyle-custom.xsl

Setting up the checkStyle plugin
`./gradlew checkStyle`

Chore: setup checkStyle plugin

---

.gitignore
build.gradle

Setup git ignore all files in /.idea and use kotlin gradle latest tool version 1.2.30
It just works and won't break the build

Setup git ignore all files in /.idea and use kotlin gradle latest tool version 1.2.30

---

app/build.gradle
app/src/main/java/template/nimbl3/TemplateApplication.kt
app/src/main/java/template/nimbl3/di/ActivityBuilder.kt
app/src/main/java/template/nimbl3/di/ActivityBuilderModule.kt
app/src/main/java/template/nimbl3/di/AppModule.kt
app/src/main/java/template/nimbl3/di/ApplicationComponent.kt
app/src/main/java/template/nimbl3/ui/MainActivity.kt
build.gradle
detekt-config.yml

In Dagger 2.10, They introduced [`dagger-android`](https://google.github.io/dagger/android.html). It look interesting. 
So I change the setup code of dagger to the new way.

Implement setup Dagger 2 to the new style

---

app/build.gradle
build.gradle

Add ktx, refactor dependencies versions format

Add ktx, refactor dependencies versions format

---

app/src/main/java/template/nimbl3/di/ApplicationComponent.kt
app/src/main/java/template/nimbl3/di/modules/ActivityBuilderModule.kt
app/src/main/java/template/nimbl3/di/modules/AppModule.kt
app/src/main/java/template/nimbl3/di/modules/GlideModule.kt
app/src/main/java/template/nimbl3/extension/ImageViewExtension.kt
app/src/main/java/template/nimbl3/extension/RxjavaExtension.kt

Moving dagger modules to /modules

---

app/proguard-rules.pro

Add proguard rule for common things we (mostly) always have:
- Crashlytics
- Dagger (sure, we have in this template)

Add proguard rule

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/nimbl3/di/modules/ActivityBuilderModule.kt
app/src/main/java/com/nimbl3/ui/main/MainActivity.kt
app/src/main/java/com/nimbl3/ui/second/SecondActivity.kt
app/src/main/res/layout/activity_second.xml
build.gradle

Resolves #34 
Add [permission dispatcher](https://github.com/permissions-dispatcher/PermissionsDispatcher) for easy permission requesting flow
- Update gradle + kotlin + small fix
- Add permission dispatcher lib: using 3.3.1 for now, we could update to 4.3.0 after migrated to androidx
- Add simple sample for camera permission requesting on SecondActivity

[#34] add permission dispatcher

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml/network_security_config.xml

Demo images can not be displayed on android P
https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted

Support cleartext traffic on android P

---

app/build.gradle
app/src/main/java/com/nimbl3/TemplateApplication.kt
app/src/main/java/com/nimbl3/di/ViewModelKey.kt
app/src/main/java/com/nimbl3/di/modules/ViewModelFactoryModule.kt
app/src/main/java/com/nimbl3/extension/ImageViewExtension.kt
app/src/main/java/com/nimbl3/extension/ToastExtension.kt
app/src/main/java/com/nimbl3/lib/viewmodel/ViewModelFactory.kt
app/src/main/java/com/nimbl3/ui/base/BaseActivity.kt
app/src/main/java/com/nimbl3/ui/base/BaseFragment.kt
app/src/main/java/com/nimbl3/ui/base/BaseViewModel.kt
app/src/main/java/com/nimbl3/ui/main/MainActivity.kt
app/src/main/java/com/nimbl3/ui/main/di/MainActivityModule.kt
app/src/main/java/com/nimbl3/ui/second/SecondActivity.kt
app/src/main/java/com/nimbl3/ui/second/di/SecondActivityModule.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_second.xml
build.gradle
data/src/main/java/com/nimbl3/data/lib/rxjava/transformers/FlowableNeverErrorTransformer.java
gradle.properties

[#35] migrate to androidx

---

build.gradle
config/jacoco.gradle
gradle/wrapper/gradle-wrapper.properties

Reverts nimblehq/android-templates#41

Revert "[#41] Update jacoco report"

---

.github/workflows/lint_and_unit_test.yml

Adding GitHub action for the template, replace bitrise
- Configure GitHub Action to do validation on each `push` - note that each project can configure further follow this base config
- Caching support for gradle dependencies artifact/dir
Check GitHub Action:

Add GitHub Action

---

RxJavaTemplate/app/build.gradle
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/di/modules/OkHttpClientModule.kt
RxJavaTemplate/build.gradle

https://github.com/nimblehq/android-templates/projects/3#card-54435439
As PM/Tester, when testing the app, they would like to inspect API request/response to make sure the content sending/receiving to/from the backend in the background correctly.
- Add [Chucker](https://github.com/ChuckerTeam/chucker) as an interceptor to intercept the API response

[Chucker Interceptor] Add Chucker Interceptor to snap the API response

---

RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/base/BaseFragment.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/base/BaseFragmentCallbacks.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/helpers/SupportEdge2EdgeHelper.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/home/HomeFragment.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/second/SecondFragment.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/webview/WebViewFragment.kt
RxJavaTemplate/app/src/main/res/layout/activity_main.xml
RxJavaTemplate/app/src/main/res/layout/fragment_home.xml
RxJavaTemplate/app/src/main/res/layout/fragment_main.xml
RxJavaTemplate/app/src/main/res/navigation/nav_graph_main.xml
RxJavaTemplate/app/src/main/res/values-v23/colors.xml
RxJavaTemplate/app/src/main/res/values-v26/colors.xml
RxJavaTemplate/app/src/main/res/values/colors.xml
RxJavaTemplate/app/src/main/res/values/styles.xml
RxJavaTemplate/build.gradle

https://github.com/nimblehq/android-templates/projects/3#card-57407267
Currently, the template doesn't support to fulfill the screen display area to the bottom navigation bar that gives a fixed black bar. This PR mainly focuses on adding `Edge-to-edge` support to our template.
- We have to set the [immersive mode](https://developer.android.com/training/system-ui/immersive#EnableFullscreen) to all screens on possible API levels (from API 26), keep the status bar and navigation bar translucent.
- On API 23-25, Android doesn't support `SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR`, we have to keep the navigation bar in black.
- On API 21-22, Android doesn't support `SYSTEM_UI_FLAG_LIGHT_STATUS_BAR` or `SYSTEM_UI_FLAG_STATUS_BAR`, we have to keep the status bar in black.
- Create …

[Support Edge to edge] 2/2 - Integrate edge to edge support helper

---

RxJavaTemplate/app/build.gradle
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/base/BaseActivity.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/base/BaseFragment.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/base/BaseNavigator.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/helpers/SupportEdge2EdgeHelper.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/MainActivity.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/MainNavigator.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/home/DataAdapter.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/home/HomeFragment.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/second/SecondBundle.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/second/SecondFragment.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/webview/WebViewBundle.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/webview/WebViewFragment.kt
RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/webview/WebViewViewModel.kt
RxJavaTemplate/app/src/main/res/layout/fragment_home.xml
RxJavaTemplate/data/build.gradle
RxJavaTemplate/domain/build.gradle
RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/data/Data.kt

https://github.com/nimblehq/android-templates/projects/3#card-52783420
Migrate RxJavaTemplate UIs to View Binding
App works normally.
https://user-images.githubusercontent.com/60863885/116226231-f13ca980-a77c-11eb-98b2-a29b081ef233.mp4

[View Binding] Part 1 - Migrate RxJavaTemplate UIs to view binding

---

CoroutineTemplate/app/build.gradle
CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/BaseActivity.kt
CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/BaseFragment.kt
CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/BaseNavigator.kt
CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/MainActivity.kt
CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/MainNavigator.kt
CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeFragment.kt
CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/second/SecondBundle.kt
CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/second/SecondFragment.kt

https://github.com/nimblehq/android-templates/projects/3#card-52783420
Migrate RxJavaTemplate UIs to View Binding
App works normally
https://user-images.githubusercontent.com/60863885/119430534-29fb7e80-bd3b-11eb-8738-67966a1dc6e2.mp4

[View Binding] Migrate CoroutineTemplate UIs to view binding

---

CoroutineTemplate/app/build.gradle
CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeFragment.kt
CoroutineTemplate/app/src/main/res/layout/fragment_home.xml
CoroutineTemplate/build.gradle
CoroutineTemplate/domain/build.gradle
CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/data/entity/UserEntity.kt
CoroutineTemplate/gradle/wrapper/gradle-wrapper.properties

https://github.com/nimblehq/android-templates/issues/86
As @luongvo said that `Jetpack Compose` integration in 1 PR is quite big which can impede the review process. So I extract the setup part here 🙏🏼 
- Add `Jetpack Compose` dependencies and update related dependencies version to support the upcoming integration of `Jetpack Compose`
- Update UI and entity to support the upcoming integration of `Jetpack Compose`
https://user-images.githubusercontent.com/13492460/124483425-863ecd00-ddd4-11eb-9afa-94ba9dd48929.mp4

Setup Jetpack Compose (CoroutineTemplate) [Part1/2]

---

RxJavaTemplate/build.gradle
RxJavaTemplate/gradle/wrapper/gradle-wrapper.properties

https://github.com/nimblehq/android-templates/projects/3#card-64963181
- Bump version accordingly to 3.1.0
- Update Gradle version

Bump version to 3.1.0 and update gradle version

---

.github/ISSUE_TEMPLATE/story_template.md

https://github.com/nimblehq/android-templates/issues/122
New [Story template](https://github.com/nimblehq/git-template/issues/16) added on `git-template` repo. Update the Story template on android-template for usage to avoid inconsistency tickets format.
- Add `story_template.md`
N/A

[#122] Add Story template

---

CoroutineTemplate/build.gradle
RxJavaTemplate/build.gradle

Bump version to 3.2.0 for development

[chore] Bump version to 3.2.0 for development

---

.github/CODEOWNERS

Nick was not on the reviewer list yet.
N/A
N/A

[Chore] Update Github reviewer list

---

CoroutineTemplate/build.gradle
RxJavaTemplate/buildSrc/src/main/java/Versions.kt

Bump version to 3.3.0 for development

[chore] Bump version to 3.3.0

---

RxJavaTemplate/app/src/main/res/font/font_circular_family.xml
RxJavaTemplate/buildSrc/src/main/java/Versions.kt

We have the code with the wrong indentation.

[chore] Adjust code format

---

CoroutineTemplate/buildSrc/src/main/java/Versions.kt
RxJavaTemplate/buildSrc/src/main/java/Versions.kt

[Chore] Bump version to 3.4.0

---

CoroutineTemplate/buildSrc/src/main/java/Versions.kt
RxJavaTemplate/buildSrc/src/main/java/Versions.kt

[Chore] Bump version to 3.5.0

---

CoroutineTemplate/buildSrc/src/main/java/Versions.kt
RxJavaTemplate/buildSrc/src/main/java/Versions.kt

[Chore] Bump version to 3.6.0

---

docs/Home.md

#121
To prevent this repository from becoming a dumping playground, we need to define some ground rules. Originally we were planning to define must-have vs nice-to-have features, but after some discussions, we realized there's a third category when the feature should not be included in the template at all. So I've revised the wording to the following:
- **Essential**
- **Optional**
- **Rejected**
In the future, we aim to include all **essential** features by default and have flags for the **optional** features, while **rejected** features are ignored. For more information, please check the code changes.
To know more about how we came to this agreement, please check the following threads:
- https://nimble-co.slack.com/archives/G41UCTGHL/p1629781993001700
- …

[#121] Update wiki-content for essential, optional and rejected features

---

.github/CODEOWNERS

Welcome to the club @ryan-conway & @kaungkhantsoe 👋  ♣️

[CHORE] Add missing members to CODEOWNERS

---

CoroutineTemplate/buildSrc/src/main/java/Versions.kt
RxJavaTemplate/buildSrc/src/main/java/Versions.kt

[CHORE] Bump version to 3.7.0

---

.github/CODEOWNERS

According to [what we discussed here](https://github.com/nimblehq/gin-templates/pull/75/files#r841554757), Github does not support defining multiple rules with the same regex `*`. The last rule will overwrite all previous ones.
- N/A
- N/A

[Chore] Correct project's maintainers info

---

CoroutineTemplate/buildSrc/src/main/java/Versions.kt
RxJavaTemplate[DEPRECATED]/buildSrc/src/main/java/Versions.kt

[Chore] Bump version to 3.8.0

---

newproject.kts
scripts/new_project.kts

#197 #198 
- Add `new_project.kts` inside `/scripts`
- Add support for arguments and store in variables for later use
Arguments can be printed in the logs:
https://user-images.githubusercontent.com/18277915/167112085-b2427bef-f10b-47d0-898b-388524bca232.mov

[#197][#198] Add `new_project.kts` and support arguments

---

scripts/new_project.kts

[#201](https://github.com/nimblehq/android-templates/issues/201)
- Clean the project folder to start fresh.
- Run clean build with Gradle: ./gradlew clean
- Remove .idea folder
- Remove .gradle folder
- Remove .git folder
- Run clean build bash command
- Remove .idea, .gradle, and .git files from new project folder
https://user-images.githubusercontent.com/32578035/167616609-d74b4723-43ce-4ec3-9b8d-31e6a6def322.mov

[#201] Clean project folder

---

scripts/new_project.kts

https://github.com/nimblehq/android-templates/issues/202
https://github.com/nimblehq/android-templates/issues/203
https://github.com/nimblehq/android-templates/issues/204
https://github.com/nimblehq/android-templates/issues/205
Rename folder structures inside the project folder
- We list the modules that need to be restructure via `modules`.
https://user-images.githubusercontent.com/60863885/168269918-eb3aebce-1c9b-489b-987f-595416a7cfd4.mp4

[#202][#203][#204][#205] Rename folder structure for existing modules

---

scripts/new_project.kts

[#209](https://github.com/nimblehq/android-templates/issues/209)
Run and show output in the logs for the following scripts:
./gradlew assembleDebug > Show "=> 🛠️ Building project..." in the log
./gradlew testStagingDebugUnitTest > Show "=> 🚓 Running tests..." in the log
Show "=> 🚀 Done! The project is ready for development"
- Run `sh gradlew -p project assembleDebug` for building
- Run `.h gradlew -p project testStagingDebugUnitTest` for unit test
- Refactor the code stracture to see the main method first then util methods
https://user-images.githubusercontent.com/32578035/169455515-98683cd9-40f9-4f8e-9d51-a6489a1d6df3.mp4

[#209] Build project and run tests

---

scripts/new_project.kts

#199
Show error message for missing/invalid arguments.
- Create `APP_PATTERN` => `^[A-Z][a-zA-Z0-9\s]*$` to validate an `app-name`.
- Create `PACKAGE_PATTERN` => `^[a-z]+(\.[a-z][a-z0-9]*)+$` to validate `package-name`.
https://user-images.githubusercontent.com/28002315/169935760-0c7edc5e-ab2e-42cf-89ec-be43087339a0.mov
https://user-images.githubusercontent.com/28002315/169935911-2f31819a-6d97-4253-918d-7dd45a4b70cf.mov
https://user-images.githubusercontent.com/28002315/169745130-5b602388-e627-413d-b208-c5d4f0cd235b.mov
https://user-images.githubusercontent.com/28002315/169745519-3bc33520-5c9b-4a82-b7a0-fa763305c9e2.mov
https://user-images.githubusercontent.com/28002315/169746184-89fa56c6-1ece-45b1-a152-5a280ebd267f.mov

[#199] Show error message for missing/invalid arguments

---

scripts/new_project.kts

#207
Rename app name within all strings.xml files inside the project folder according to app-name.
https://user-images.githubusercontent.com/28002315/169774187-3b4967a9-0cd6-4386-b6cd-26f0abcd85ad.mov

[#207] Rename app name in strings.xml

---

CoroutineTemplate/buildSrc/src/main/java/Versions.kt

[CHORE] Bump version to 3.9.0

---

README.md

Quick update for the light/dark logo visibility.
Minor update
Before:
https://user-images.githubusercontent.com/13435717/173321532-2efe3e86-28ff-4559-8bbe-cdb3e924c5bb.mov
After:
https://user-images.githubusercontent.com/13435717/173321405-40354c78-1f3d-4ed5-98bc-77b5b84ce9f7.mov

Support light/dark logo on README

---

docs/Home.md

#172
Added a section to `Home.md` to define how we vote on RFC's

[#172] Add section for voting process to Wiki

---

scripts/new_project.kts

[#241](https://github.com/nimblehq/android-templates/issues/241)
The new project script must be able to generate projects with names such as sample-compose or android-templates
This is currently not possible with the script.
- App name with the first letter as lower case should be accepted
- App name which contains - should be accepted
- App name in strings.xml should show correctly (ex: sample-compose -> Sample Compose)
- App name in application class should show correctly (ex: sample-compose -> SampleComposeApplication)
- Update `app-name` regex check to be able to accept both `My App` and `my-app` format when initializing new project
- Whenever accepting `app-name` in `-` format, convert the value to `My App` format and reassign to `appName` variable so that everything works the same …

[#241] Update kscript for app name argument

---

README.md
scripts/new_project.kts

Closes #234
Old bash script have --help function which prints the instruction of how to use the script to create a new project but new script doesn't have one.
Add additional parameter and check if the passed parameter is `help` and show message

[#234] Add help function for kscript

---

scripts/new_project.kts

Closes #273
`testStagingDebugUnitTest` only executes tests for `app` module, so execute command for each module separately
Please check "Verify generating new project from template" logs
https://github.com/nimblehq/android-templates/runs/7893007827?check_suite_focus=true

[#273] Fix incorrect step for running tests in `new_project.kts`

---

.cicdtemplate/.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Closes #266 
According to [this discussion](https://nimble-co.slack.com/archives/CSQG2QXFX/p1657255264166839), we need to adopt the new pull request template from [git-templates](https://github.com/nimblehq/git-template) repository
Update the following files according to [this PR](https://github.com/nimblehq/git-template/pull/27)
- `.github/PULL_REQUEST_TEMPLATE.md`
- `.cicdtemplate/.github/PULL_REQUEST_TEMPLATE.md`
N/A

[#266] Update description of pull request template

---

sample-compose/buildSrc/src/main/java/Versions.kt
sample-xml/buildSrc/src/main/java/Versions.kt
template/buildSrc/src/main/java/Versions.kt

Bumped version from `3.11.0` to `3.12.0`

[Chore] Bump version to 3.12.0

---

template/buildSrc/src/main/java/Versions.kt

closes #304 
- Updated Robolectric version to 4.8.2

[#304] Fix failing instrumentation tests

---

sample-compose/buildSrc/src/main/java/Versions.kt
sample-xml/buildSrc/src/main/java/Versions.kt
template/buildSrc/src/main/java/Versions.kt
version.properties

- Bumped version from `3.12.0` to `3.13.0` for sample projects & script
- Set version to `1.0.0` for template

[Chore] Update versions

---

sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/ErrorMapping.kt
sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeFragment.kt
sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeViewModel.kt
sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/extensions/ResponseMapping.kt
sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/repository/RepositoryImpl.kt
sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/response/ErrorResponse.kt
sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/extensions/ResponseMappingTest.kt
sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/test/MockUtil.kt
sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/exceptions/Exceptions.kt
sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/model/Error.kt
sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/ErrorMapping.kt
sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/base/BaseViewModel.kt
sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeFragment.kt
sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeViewModel.kt
sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/extensions/ResponseMapping.kt
sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/repository/RepositoryImpl.kt
sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/response/ErrorResponse.kt
sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/extensions/ResponseMappingTest.kt
sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/test/MockUtil.kt
sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/exceptions/Exceptions.kt
sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/model/Error.kt

https://github.com/nimblehq/android-templates/issues/212
- Bring logic updates in [this PR](https://github.com/nimblehq/android-templates/pull/311) from the `template` project into `sample` projects.
Add `flowTransform` to map and handle custom errors as Flow in data layer for:
- Compose sample.
- XML sample.
N/A

[#212] [2/2 - Sample] Add flowTransform to map and handle custom errors as Flow in data layer

---

.github/workflows/draft-new-release.yml
.github/workflows/verify_newproject_script.yml
README.md
version.properties

Closes #265 
- Define the versions for `Kotlin` & `Kscript` so that the workflows are aligned
- Updated `README.md` to inform users on version requirements
After running `source version.properties` it will create a variable for every key-value pair
https://github.com/nimblehq/android-templates/actions/runs/3351884688/jobs/5553634651

[#265] Add dependency versions for workflows to a properties file

---

sample-compose/buildSrc/src/main/java/Versions.kt
sample-xml/buildSrc/src/main/java/Versions.kt
version.properties

Bumped version from 3.13.0 to 3.14.0

[Chore] Bump version to 3.14.0

---

.github/CODEOWNERS

@thiennguyen0196 a.k.a Bruce was missing from the list  👋 
N/A
N/A

[Chore] Update reviewer list

---

.github/workflows/review_pull_request.yml
.github/workflows/run_detekt_and_unit_tests.yml
.github/workflows/verify_newproject_script.yml
template/app/build.gradle.kts
template/app/src/main/AndroidManifest.xml
template/app/src/main/java/co/nimblehq/template/extension/ViewModelExt.kt
template/build.gradle.kts
template/buildSrc/src/main/java/Versions.kt
template/data/build.gradle.kts
template/data/src/test/java/co/nimblehq/template/data/extensions/ResponseMappingTest.kt
template/data/src/test/java/co/nimblehq/template/data/repository/RepositoryTest.kt
template/domain/build.gradle.kts
template/domain/src/test/java/co/nimblehq/template/domain/usecase/UseCaseTest.kt
template/gradle/wrapper/gradle-wrapper.properties

https://github.com/nimblehq/android-templates/issues/163
https://github.com/nimblehq/android-templates/issues/191
https://github.com/nimblehq/android-templates/issues/300
- Java 1.8 is old, we should upgrade it to 11 in order to use latest Gradle or Kotlin version
- Upgrade Compile and Target SDK version from 30 to 33
- Update Gradle to version 7+
- Upgrade JDK 11 for CI Pull Request Review and Run Detekt/Unit Test
- Upgrade Gradle to 7.3.0
- Upgrade min Android from 23 -> 24
- Upgrade Java from 8 to 11
N/A

[#163][#191][#300]   Upgrade JDK, SDK, Gradle & Kotlin

---

sample-compose/buildSrc/src/main/java/Versions.kt
sample-xml/buildSrc/src/main/java/Versions.kt
version.properties

Bumped version from 3.14.0 to 3.15.0

[Chore] Bump version to 3.15.0

---

sample-compose/buildSrc/src/main/java/Versions.kt
sample-xml/buildSrc/src/main/java/Versions.kt
version.properties

Bumped version from `3.15.0` to `3.16.0`

[Chore] Bump version to 3.16.0

---

.cicdtemplate/.github/workflows/bump_version.yml
.github/workflows/bump_version.yml

Close https://github.com/nimblehq/android-templates/issues/301
- Add script bump version and create PR for XML and Compose templates
- Input version code manually
- Bump version XML template
- Bump version Compose template
- Bump version for the script
- Create Pull Request
https://github.com/nimblehq/android-templates/pull/385

[#301] Automate New version bumping by Github action

---

sample-compose/buildSrc/src/main/java/Versions.kt
sample-xml/buildSrc/src/main/java/Versions.kt
version.properties

Bumped version from `3.16.0` to `3.17.0`

[Chore] Bump version to 3.17.0

---

.github/CODEOWNERS

Update team lead in code owners file
N/A

[Chore] Update code owners

---

.github/PULL_REQUEST_TEMPLATE/RELEASE_TEMPLATE.md

Closes #297 
Simple description update for our release template
N/A

[#297] Update release-template description

---

.github/wiki/Home.md

closes #378 
- Removed all references to optional features
- Updated the content in `How do we vote on an issue?` section
- Created separate sections detailing how to open an issue and when an issue is approved or rejected
N/A

[#378] Update Wiki to remove optional features and clarify voting labels

---

.codemagic/codemagic.yml
codemagic.yaml

- https://github.com/nimblehq/android-templates/issues/448
I'll split the task into 2 parts:
**Part 1** :
**Part 2** :
The document for Codemagic can be found here: https://docs.codemagic.io/yaml-basic-configuration/yaml-getting-started/#instance-type
I decided to include the script for the `template-xml` since we have it in the current `github action` workflow.

[#448][Part1/2] Initiate codemagic script and implement unit test script for PR and Push event

---

.github/CODEOWNERS

Update add @eeeeaa as code owner
N/A

[Chore] Add tiger as codeowner
