nimblehq/android-templates

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/AndroidManifest.xml
- app/src/main/java/template/nimbl3/di/AppGlideModule.kt
- app/src/main/java/template/nimbl3/extension/ImageViewExtension.kt
- app/src/main/java/template/nimbl3/ui/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
- app/src/test/java/template/nimbl3/ui/ExampleUnitTest.kt
- build.gradle
Setting up Glide for image loading as this is an absolute need for every application.
- ImageView extension with Glide inner plugged usage is simple as:
```
imv.setImageUrl("url")
```
- With vs Without proguard application size: `1.18Mb vs 3.07Mb`
- Tested loading:
> Feature: setup Glide for image loading

- config/jacoco.gradle
Jacoco doesn't report for java classes, coverage is higher than expected https://stackoverflow.com/questions/53374692/android-java-byte-code-missing-after-update-gradle-and-build-tools
- Java Byte Code (generated .class files) is under `$buildDir/intermediates/javac/developerDebug/compileDeveloperDebugJavaWithJavac/classes` instead after upgrated gradle https://stackoverflow.com/questions/53374692/android-java-byte-code-missing-after-update-gradle-and-build-tools
> Update java byte code classes path for jacoco

- build.gradle
- config/jacoco.gradle
- gradle/wrapper/gradle-wrapper.properties
The report has shown only one module when we open index.html in browser from both modules.
This is a step for checking.
- run ./gradlew jacocoTestReport testStagingDebugUnitTest
- open index.html in browser from the data module, You will see the report only one module that is "com.nimble3.data..."
- open index.html in browser from app module, The report has shown the same with data module that is "com.nimble3.data..." but it should be show "com.nimble3.ui..." or both modules.
Update the directory file in jacoco.gragle script.
We need to define a directory file for both app and data modules.
Run script -> ./gradlew jacocoTestReport
> [#41] Update jacoco report

- app/build.gradle
- build.gradle
- config/jacoco.gradle
- data/build.gradle
- gradle/wrapper/gradle-wrapper.properties
The report has shown only one module when we open index.html in browser from both modules.
This is a step for checking.
- run ./gradlew jacocoTestReport testStagingDebugUnitTest
- open index.html in browser from the data module, You will see the report only one module that is "com.nimble3.data..."
- open index.html in browser from app module, The report has shown the same with data module that is "com.nimble3.data..." but it should be show "com.nimble3.ui..." or both modules.
Update the directory file task jacoco in jacoco.gragle script.
We need to define a directory file for both app and data modules.
Run script -> ./gradlew jacocoTestReport, ./gradlew jacocoTestReport testStagingDebugUnitTest
> Update jacoco report

- app/src/main/java/co/nimblehq/ui/ErrorMapping.kt
- app/src/main/java/co/nimblehq/ui/base/BaseActivity.kt
- app/src/main/java/co/nimblehq/ui/base/BaseFragment.kt
- app/src/main/java/co/nimblehq/ui/base/BaseViewModel.kt
- app/src/main/java/co/nimblehq/ui/screens/home/HomeViewModel.kt
- app/src/test/java/co/nimblehq/ui/screens/home/HomeViewModelTest.kt
- detekt-config.yml
- Currently, whenever a task is being subscribed, we always try to show and hide the loading by `doOnSubscribe` and `doFinally` (or sometimes `doOnError`). 
For example:
```
getExampleDataUseCase
.execute(Unit)
.doOnSubscribe { _showLoading.onNext(true) }
.toObservable()
```
```
_refresh
.flatMap { fetchApi() }
.subscribeBy(
onNext = {
_data.onNext(it)
_showLoading.onNext(false)
},
onError = _error::onNext
)
.addToDisposables()
```
This way will inject multiple items into `_showLoading` and made our tests hard to check and messy.
```
loadingObserver
.assertNoErrors()
.assertValues(false, true, true, true, false, false, false)
```
- It also makes us hard to manage to show or hide loading when there are multiple parallel running tasks in VM
- Keep a counted object of `_showLoading` state, …
> [Feature] Optimize loading handling by adding `doShowLoading` operator

- .github/CODEOWNERS
Need to automate adding reviewers when opening new PR process to have all @nimblehq/android-chapter members participation. 🤓 
Give a kudos to Github for [this CODEOWNERS config support](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) ⭐  
All @nimblehq/android-chapter members now should be added automatically into new open PRs ✅
> [CHORE] Add Github CODEOWNERS config: auto-request all members for code review

- .github/workflows/lint_and_unit_test.yml
Updating the workflow file to get rid of the `cd` command. It's more declarative when using GitHub action `working_directory`.
The CI/CD pipeline should remain functioning the same now
Pending for the CI status.
> Update github action with working_directory instead of cd

- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/chore_template.md
- .github/ISSUE_TEMPLATE/feature_template.md
- .github/PULL_REQUEST_TEMPLATE.md
https://github.com/nimblehq/android-templates/issues/96
- Update current `PULL_REQUEST_TEMPLATE.md`
- Add `ISSUE_TEMPLATE` copied from `git-template`
*Note*: Please notice that `chore_template.md` is not officially merged yet ([Opening PR](https://github.com/nimblehq/git-template/pull/14)). I will update later if any change on that PR 🙏
> [96] Update .github template

- RxJavaTemplate/app/build.gradle
- RxJavaTemplate/app/src/test/java/co/nimblehq/rxjava/ui/screens/MainNavigatorTest.kt
- RxJavaTemplate/app/src/test/java/co/nimblehq/rxjava/ui/screens/home/HomeViewModelTest.kt
- RxJavaTemplate/build.gradle
- RxJavaTemplate/data/build.gradle
- RxJavaTemplate/domain/build.gradle
https://github.com/nimblehq/android-templates/issues/105
As stated from #105 that when trying to run the unit tests, we are having some failed issues due to the current Mockito library in the app - `com.nhaarman.mockitokotlin2:mockito-kotlin`. Need to update to use a latest library and fix all tests failed issues.
- Resolved #105 by updating to use a new official library: `org.mockito.kotlin:mockito-kotlin`.
- All the code syntax and test logic is persisted and no need to update.
All tests are passed, we can run and build the app and tests successfully without any issue:
> [#105] Update Mockito library to fix some unit tests fail issues for RxJavaTemplate

- CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/di/modules/StorageModule.kt
- CoroutineTemplate/build.gradle
- CoroutineTemplate/domain/build.gradle
- CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/extension/SharedPreferencesExt.kt
- CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/storage/BaseSharedPreferences.kt
- CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/storage/EncryptedSharedPreferences.kt
- CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/storage/NormalSharedPreferences.kt
- RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/storage/BaseSharedPreferences.kt
https://github.com/nimblehq/android-templates/issues/98
We are using SharedPreferences on most current projects for caching data. Creating BaseSharedPreferences for common usage.
- Bring `SharedPreferences` implementation from RxJavaTemplate to this CoroutineTemplate as per [comment](https://github.com/nimblehq/android-templates/pull/101#issuecomment-871204647) from @hoangnguyen92dn.
- Adjust some DI implementations to match with this template's DI library version.
- Just under the hood optimization, no visual changes. The app is built and running successfully:
> [98] Add BaseSharedPreferences to CoroutineTemplate

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/RELEASE_TEMPLATE.md
Resolves #112 
As part of the engineering initiatives, this PR adds the Github template for the release pull requests that match Nimble's [convention](https://nimblehq.co/compass/development/version-control/release-management/#release-pull-request).
The implementation is identical with https://github.com/nimblehq/git-template/pull/15. 
Github supports multiple [templates for issues and pull requests](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). For example, to define multiple pull request templates, simply define them like this:
```bash
.github
└── PULL_REQUEST_TEMPLATE
├── normal_template.md
└── release_template.md
```
But unlike issue templates - when opening a new issue, Github will show a …
> Add the Github release PR template

- .github/workflows/publish_docs_to_wiki.yml
- README.md
- docs/Home.md
https://github.com/nimblehq/android-templates/issues/119
- Add link to Wiki in READM.me
- Add first doc (`Home.md`)
- Add GitHub action for publishing docs to Wiki
The idea was taken from [wiki-page-creator-action](https://github.com/Decathlon/wiki-page-creator-action), however this has its limitations:
- No support for removing Wiki pages with pull requests: [issue](https://github.com/Decathlon/wiki-page-creator-action/issues/11)
- We can't reference images with a relative path
So to solve both of these, we created our own solution, based from the following: [github-wiki-action](https://github.com/Andrew-Chen-Wang/github-wiki-action) 🚀
The Wiki for this repository is stored [here](https://github.com/nimblehq/android-templates/wiki), meaning it's independent of [our …
> [#119] Add action to publish docs to Wiki

- CoroutineTemplate/app/build.gradle.kts
- CoroutineTemplate/app/src/debug/AndroidManifest.xml
- CoroutineTemplate/app/src/debug/java/co/nimblehq/coroutine/EmptyHiltActivity.kt
- CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/extension/ViewModelExt.kt
- CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/BaseFragment.kt
- CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeFragment.kt
- CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/test/TestModules.kt
- CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/test/ViewModelExt.kt
- CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/ui/BaseFragmentTest.kt
- CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/ui/screens/home/HomeFragmentTest.kt
- CoroutineTemplate/app/src/test/resources/robolectric.properties
- CoroutineTemplate/buildSrc/src/main/java/Versions.kt
https://github.com/nimblehq/android-templates/issues/83
We haven't written any unit testing part for the presentation layer. This PR is to set up all necessary pieces so we can easily write the unit test for Fragment/ Activity later.
Continue the work for CoroutineTemplate from #137 
https://user-images.githubusercontent.com/60863885/139396980-7a5fa194-e239-4c42-bc1c-18e67f56dadb.mov
> [#83] Setup the unit testing part for Coroutine Template

- .github/ISSUE_TEMPLATE/rfc_template.md
https://github.com/nimblehq/android-templates/issues/146
Following the Compass repository, there is a template for creating the RFC when the issue needs to be voted for agreement by the team. Android repository is lacking this template.
Copy RFC template from [compass repository](https://github.com/nimblehq/compass/blob/development/.github/ISSUE_TEMPLATE/rfc_template.md)
The RFC should be shown when creating a new issue
> [#146] Add RFC template

- .github/workflows/verify_newproject_script.yml
- newproject.sh
https://github.com/nimblehq/android-templates/issues/133
As we discussed recently in the Retrospective Meeting, the current process to initialize a project via the newproject.sh script is not being tested when the CI runs. This causes us into trouble when there are changes under the hood of the template implementation that breaks the script or are executed but the project is not buildable.
The solution does not only do we run the unit test on the template like a normal project, but we have to also test our init script that works as expected.
Here is the solution to verify `newproject.sh` script:
- Firstly, I added `gradle` command to build the project and execute UnitTest on the generated project to make sure the script works properly.
- The second step is adding a new workflow to execute …
> [#133] Adding the test step for the newproject.sh test script

- .github/workflows/publish_docs_to_wiki.yml
- .github/workflows/run_detekt_and_unit_tests.yml
#165 
There's a `-` too many, which is causing the workflows to fail.
Please check the issue for more information
I found the solution from here: https://github.com/einaregilsson/beanstalk-deploy/issues/2#issuecomment-555894644
Checks are all succeeded: https://github.com/nimblehq/android-templates/pull/166/checks
> [#165] Fix Github Actions error

- RxJavaTemplate/build.gradle.kts
- RxJavaTemplate/buildSrc/src/main/java/Versions.kt
#155 
- JCenter is deprecated, so replace it with MavenCentral. 
- Upgrade dependency versions to resolve CI issue caused by migration
Only make this change for RxJavaTemplate, as it's already integrated for CourotineTemplate
https://user-images.githubusercontent.com/18277915/159412531-cc27b904-bf45-4fad-8754-93d125d59963.mp4
> [#155] Replace `jCenter()` with `mavenCentral()`

- .github/CODEOWNERS
- Rework the `CODEOWNERS` in the subdirectory `.github` to follow the standardized format used on all project templates.
- Reorder the list of team members in alphabetical order.
All project template repositories now have official leads so it is crucial to have it documented.
> [CHORE] Update the project's maintainers info

- RxJavaTemplate/.gitignore
- RxJavaTemplate/app/.gitignore
- RxJavaTemplate/config/jacoco.gradle.kts
- RxJavaTemplate/data/.gitignore
- RxJavaTemplate/domain/build.gradle.kts
https://github.com/nimblehq/android-templates/issues/179
After migrating [Jacoco config to Kotlin DSL](https://github.com/nimblehq/android-templates/pull/145), Jacoco is reporting **incorrect** coverage with some redundant packages and classes.
- In Kotlin DSL, we need to add `**/` prefix for package excludes.
- There are also some more packages and classes that should be excluded, such as Hilt, Nav Component, Data binding, Kotlin enum, etc.
```
dagger.hilt.internal.aggregatedroot.codegen
dagger.hilt.internal.processedrootsentinel.codegen
hilt_aggregated_deps
```
|  After | Before |
| - | - |
| <img width="521" alt="image" src="https://user-images.githubusercontent.com/16315358/161622990-a58abcce-f765-422a-b1d7-f813330aeb28.png"> | …
> [#179] Fix: incorrect Jacoco coverage report after migrating to Kotlin DSL

- .github/workflows/review_pull_request.yml
- .github/workflows/run_detekt_and_unit_tests.yml
- CoroutineTemplate/.gitignore
- CoroutineTemplate/README.md
- CoroutineTemplate/app/build.gradle.kts
- CoroutineTemplate/buildSrc/src/main/java/Versions.kt
- CoroutineTemplate/buildSrc/src/main/java/plugins/jacoco-report.gradle.kts
- CoroutineTemplate/config/jacoco.gradle.kts
- CoroutineTemplate/data/build.gradle.kts
- CoroutineTemplate/data/src/test/java/co/nimblehq/coroutine/data/repositoryimpl/UserRepositoryTest.kt
- CoroutineTemplate/domain/build.gradle.kts
- CoroutineTemplate/domain/src/test/java/co/nimblehq/coroutine/domain/usecase/GetUsersUseCaseTest.kt
- Dangerfile
https://github.com/nimblehq/android-templates/issues/169
Jacoco is currently not supported for `CoroutineTemplate`, however, it is working correctly for `RxJavaTemplate`
In `.github/workflows/review_pull_request.yml` there's a pending TODO
Let's make sure Jacoco can run the tests and generate a report in the CI successfully.
- From what we achieved in this PR https://github.com/nimblehq/android-templates/pull/137, we can set up the Jacoco report for `app` module easily, however, one caution is:
- We need to force to use Jacoco version `0.8.7` to bypass this issue https://youtrack.jetbrains.com/issue/KT-44757 on `Kotlin 1.5` 🤓 
- Add Jacoco report to `data` module. This is an Android library module without app flavor so there is a change in `classDirectoriesTree` and `dependsOn` …
> [#169] Add Jacoco to CoroutineTemplate

- scripts/new_project.kts
[#200](https://github.com/nimblehq/android-templates/issues/200)
- Show "=> 🐢 Initializing new project..." in the logs
- Initialize project folder by copying CoroutineTemplate recursively
- Rename project folder according to trimmed app-name
- If app-name="My Project", then the project folder must be named "MyProject"
- Create new folder for the project and name the project without space
- Copy files to new folder recursively
- Enable `gradlew` to be `executable`
https://user-images.githubusercontent.com/32578035/167353504-8e7f22e0-24b2-4a18-a9f3-8f9c5e9dd10e.mov
> [#200] Initialize new project directory and copy files recursively

- scripts/new_project.kts
[#206](https://github.com/nimblehq/android-templates/issues/206)
- Show "=> 🔎 Renaming package name within files..." in the log
- Rename package name and imports according to package-name, including AndroidManifest.xml
- Read each file contents and replace `old package name` with `new package name`
> [#206] Rename package names within files

- scripts/new_project.kts
#206 
After renaming the package name within files, the `debug.keystore` got corrupted.
So the generated project was no longer buildable:
My guess is that `debug.keystore` contains the package name of `CoroutineTemplate` 💭 
**Solution**? Skip `debug.keystore` when renaming the package name within files
The generated project is buildable again:
https://user-images.githubusercontent.com/18277915/168966107-1223c392-8e45-4747-9d9d-26f999d99d54.mov
> [#206] Fix corrupted `debug.keystore` after renaming

- scripts/new_project.kts
#208 
Rename application class according to `app-name` argument, there are two processes:
1. Rename application class file (Ex: `CoroutineTemplateApplication` to `MyProjectApplication`)
2. Rename application class in `AndroidManifest.xml`
https://user-images.githubusercontent.com/18277915/169508816-15042a0c-6553-489f-b70c-b262cd2323b0.mov
> [#208] Rename application class

- CoroutineTemplate/data/build.gradle.kts
#233 
Enable `isMinifyEnabled` for `data` in CoroutineTemplate (for release variant)
App is buildable in release variant (after manually adding `release.keystore`):
https://user-images.githubusercontent.com/18277915/173030844-3219dbc3-06ce-4446-ab6f-77acf21d9072.mov
> [#233] Enable `isMinifyEnabled` for `data`

- .github/release-drafter-config.yml
- .github/workflows/draft-new-release.yml
- .github/workflows/release-drafter.yml
- scripts/get_version.kts
https://github.com/nimblehq/android-templates/issues/100
Add a workflow to automatically generate a release note and tag when pushing changes to `main`.
- Added `release-drafter.yml` to be triggered when pushing changes to `main`.
- Used [release-drafter/release-drafter](https://github.com/release-drafter/release-drafter) action to generate a draft release. The content would be the same as our current format. Please suggest emojis if you want them in the content.
> Note: the config file _must_ be on the default branch, i.e, `develop` in our case.
- Added `get_version.kts` to get the version from the commit message passed as an argument. Special thanks to @Tuubz for helping with KScript.
Closes #100
> [#100] Add new workflow to generate release note and version tag automatically

- scripts/new_project.kts
Closes #269 
`Runtime.getRuntime().exec(String)` will partition a command automatically, based on white spaces.
If a file path contains a white space, it will not be able to find the file and result in an error.
-> **Example**: "Desktop/My Projects/android-templates" -> ["Desktop/My", "Projects/android-templates"]
-> **Reference**: https://stackoverflow.com/questions/33077129/java-runtime-exec-with-white-spaces-on-path-name
Preferably I don't want to pass an array of Strings, so initially, so I tried the following:
- I tried escaping the white space (`\`)
- I tried encoding the white space (`%20)`
- I tried wrapping the file path with quotes
- I tried splitting up the command into an array, with regular expressions
Unfortunately, I couldn't make it work with these approaches
Please let me …
> [#269] Fix file path error when executing new_project.kts

- scripts/new_project.kts
- template/.gitignore
- template/README.md
Closes #275
- Update forgotten files when running `new_project.kts`:
- `app/build.gradle.kts` : Rename package name in `applicationId`
- `jacoco-report.gradle.kts` : Rename package name in `packagesExcluded`
- Refactor `SEPARATOR` const variables so they can be grouped
- Clean up `README.md`: To keep it simple, just remove the link
- Clean up `.gitignore`
https://user-images.githubusercontent.com/18277915/184790619-1a4b155d-8d24-4d07-bc5f-bfc9db217da3.mp4
> [#275] Fix references when generating a new project

- scripts/new_project.kts
closes #285 
- Added `joinToString(" ")` call when printing `command` to print the issued command
> [#285] Print failed command when execution fails

- scripts/new_project.kts
Closes #282 
Fixed issue with `new_project.kts` not running properly from root folder.
Also fixed issue when generating a new project and file path contains `scripts` anywhere before the last segment.
- Added check if current directory ends with `/scripts`
- If yes, remove last segment.
- If no, keep path as is and append `/`
Note: PoW captured by printing `rootPath`, `projectPath` and `ProjectFolderName` values
Old script from path that contains `script`
New script from path that contains `scripts`
New script from root folder
New script from `/scripts` folder
> [#282] Support running new_project.kts from project root folder

- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/ItemList.kt
Closes #242 
According to [this discussion](https://github.com/nimblehq/android-templates/pull/281#discussion_r954672390), we need to add a divider for the last item in Compose sample for the sake of consistency on both sample
> [#242] Add divider for last item in Compose sample

- template/app/src/main/java/co/nimblehq/template/ui/screens/compose/HomeComposeViewModel.kt
- template/app/src/main/java/co/nimblehq/template/ui/screens/xml/HomeViewModel.kt
- template/data/build.gradle.kts
- template/data/src/main/java/co/nimblehq/template/data/repository/RepositoryImpl.kt
- template/data/src/test/java/co/nimblehq/template/data/repository/RepositoryTest.kt
- template/domain/build.gradle.kts
- template/domain/src/main/java/co/nimblehq/template/domain/repository/Repository.kt
- template/domain/src/main/java/co/nimblehq/template/domain/usecase/UseCase.kt
- template/domain/src/main/java/co/nimblehq/template/domain/usecase/UseCaseResult.kt
- template/domain/src/test/java/co/nimblehq/template/domain/usecase/UseCaseTest.kt
Resolves https://github.com/nimblehq/android-templates/issues/213
- Apply to use [Flow](https://developer.android.com/kotlin/flow) to transfer the data from `Repository` through `UseCase` to `ViewModel`.
- Get rid of duplicating a new **try/catch** block in both `UseCase` and `Repository` when implementing https://github.com/nimblehq/android-templates/issues/212 as we can't access `retrofit objects` such as [HttpException](https://square.github.io/retrofit/2.x/retrofit/retrofit2/HttpException.html) in UseCase layer.
- Get rid of using a custom `UseCaseResult` to transfer data and exception from Usecase to ViewModel.
- Update all ViewModel logics and samples to adapt new structure.
- I don't think we should apply to use a custom `UseCaseResult` or even built-in …
> [#213] [1/2 - Template] Apply to use Flow + get rid of custom UseCaseResult

- scripts/new_project.kts
- version.properties
closes #264 
Versioning is useful so that the script can be reported or referenced with the version.
This issue consists of three parts:
**Part 1 : Set-up the properties file**
1. Add `version.properties` to the root folder (if it doesn't already exist)
2. Add a property to indicate the current version of `new_project.kts` → `3.12.0` **(A)** 
**Part 2 : Use the properties file**
When running `new_project.kts`, it must show a message: `"=> Running new project script version **(A)**... 👋" 
**Part 3 : Update documentation**
Update output message with **(A)** when executing `kscript new_project.kts --help`
- Add `version.properties` file at the root folder
- Add property with value
- Show version message when executing `kscript new_project.kts --help`
> [#264] Add version for new_project.kts to a properties file

- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeViewModel.kt
- sample-compose/data/build.gradle.kts
- sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/repository/RepositoryImpl.kt
- sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/repository/RepositoryTest.kt
- sample-compose/domain/build.gradle.kts
- sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/repository/Repository.kt
- sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/UseCase.kt
- sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/UseCaseResult.kt
- sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/UseCaseTest.kt
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeViewModel.kt
- sample-xml/data/build.gradle.kts
- sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/repository/RepositoryImpl.kt
- sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/repository/RepositoryTest.kt
- sample-xml/domain/build.gradle.kts
- sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/repository/Repository.kt
- sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/usecase/UseCase.kt
- sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/usecase/UseCaseResult.kt
- sample-xml/domain/src/test/java/co/nimblehq/sample/xml/domain/usecase/UseCaseTest.kt
- template/data/src/main/java/co/nimblehq/template/data/repository/RepositoryImpl.kt
- template/data/src/test/java/co/nimblehq/template/data/repository/RepositoryTest.kt
Resolves https://github.com/nimblehq/android-templates/issues/213
- Apply to use [Flow](https://developer.android.com/kotlin/flow) to transfer the data from `Repository` through `UseCase` to `ViewModel`.
- Get rid of duplicating a new **try/catch** block in both `UseCase` and `Repository` when implementing https://github.com/nimblehq/android-templates/issues/212 as we can't access `retrofit objects` such as [HttpException](https://square.github.io/retrofit/2.x/retrofit/retrofit2/HttpException.html) in UseCase layer.
- Get rid of using a custom `UseCaseResult` to transfer data and exception from Usecase to ViewModel.
- Update all ViewModel logics and samples to adapt new structure.
- I don't think we should apply to use a custom `UseCaseResult` or even built-in …
> [#213] [2/2 - Sample] Apply to use Flow for Compose and XML samples

- README.md
Resolved https://github.com/nimblehq/android-templates/issues/307
Update README to be more clear about where should run the script to generate the new project.
I have 3 options:
1. To tell the consumer to run `cd` command first.
2. To tell the consumer to run the script inside of the `scripts` directory as a remark after describing
> Run `kscript new_project.kts` to create a new project with the following arguments:
3. Update the `kscript new_project.kts` to `kscript scripts/new_project.kts`
I prefer the **option 1** since it's simpler and don't make the command to be too long in case we will have many more options in the script in the future.
> [#307] Update README for more clear about where should run the script

- sample-compose/app/build.gradle.kts
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/di/modules/OkHttpClientModule.kt
- sample-compose/buildSrc/src/main/java/Versions.kt
- sample-xml/app/build.gradle.kts
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/di/modules/OkHttpClientModule.kt
- sample-xml/buildSrc/src/main/java/Versions.kt
- template/app/build.gradle.kts
- template/app/src/main/java/co/nimblehq/template/di/modules/OkHttpClientModule.kt
- template/buildSrc/src/main/java/Versions.kt
https://github.com/nimblehq/android-templates/issues/294
Add Chucker library to
- Template
- Compose sample
- XML sample
- Add Chucker library to Template, Compose sample, and XML sample
- Use Hilt to provide Chucker interceptor
- We will only apply Chucker for debug builds
**Template**
https://user-images.githubusercontent.com/13492460/198258179-1db02efa-e1d9-4912-9346-68201286aa42.mp4
**Compose sample**
https://user-images.githubusercontent.com/13492460/198258852-0834b4eb-d992-4393-8174-4847c9ecbd53.mp4
**XML sample**
https://user-images.githubusercontent.com/13492460/198258920-de6f4918-0749-41da-ba59-c1c2c333254c.mp4
> [#294] Add Chucker library

- sample-compose/buildSrc/src/main/java/Versions.kt
- sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/xml/HomeFragmentTest.kt
- sample-xml/buildSrc/src/main/java/Versions.kt
Closes #346 
- Fix failing `HomeFragmentTest.kt` in `sample-xml`
- Update robolectrics versions for sample projects so it aligned with `template`
> [#346] Fix failing sample xml test

- .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
- .cicdtemplate/.github/workflows/review_pull_request.yml
- .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
- gradle-wrapper.properties
- gradle/wrapper/gradle-wrapper.properties
- sample-compose/app/build.gradle.kts
- sample-compose/app/src/main/AndroidManifest.xml
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/extension/ViewModelExt.kt
- sample-compose/build.gradle.kts
- sample-compose/buildSrc/src/main/java/Versions.kt
- sample-compose/data/build.gradle.kts
- sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/extensions/ResponseMappingTest.kt
- sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/repository/RepositoryTest.kt
- sample-compose/domain/build.gradle.kts
- sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/UseCaseTest.kt
- sample-compose/gradle/wrapper/gradle-wrapper.properties
- sample-xml/app/build.gradle.kts
- sample-xml/app/src/main/AndroidManifest.xml
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/extension/ViewModelExt.kt
- sample-xml/build.gradle.kts
- sample-xml/buildSrc/src/main/java/Versions.kt
- sample-xml/data/build.gradle.kts
- sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/extensions/ResponseMappingTest.kt
- sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/repository/RepositoryTest.kt
- sample-xml/domain/build.gradle.kts
- sample-xml/domain/src/test/java/co/nimblehq/sample/xml/domain/usecase/UseCaseTest.kt
- sample-xml/gradle/wrapper/gradle-wrapper.properties
https://github.com/nimblehq/android-templates/issues/163
https://github.com/nimblehq/android-templates/issues/191
https://github.com/nimblehq/android-templates/issues/300
- Java 1.8 is old, we should upgrade it to 11 in order to use latest Gradle or Kotlin version
- Upgrade Compile and Target SDK version from 30 to 33
- Update Gradle to version 7+
For XML and Compose sample:
- Upgrade JDK 11 for CI Pull Request Review and Run Detekt/Unit Test
- Upgrade Gradle to 7.3.0
- Upgrade min Android from 23 -> 24
- Upgrade Java from 8 to 11
N/A
> [#163][#191][#300] Upgrade JDK, SDK, Gradle & Kotlin for Sample

- .github/wiki/Home.md
- .github/workflows/verify_newproject_script.yml
- README.md
- scripts/new_project.kts
- Closes #336 
- Closes #338 
Update `new_project.kts` to be able to generate either `xml` or `compose` template project.
- Add a new flag called `template`, the value can either be `xml` or `compose`
- Ensure a project can be generated correctly for both options
- Ensure the help message is up-to-date
- Update `verify_newproject_script.yml` so the CI still works correctly
- Add keys and names for both `xml` and `compose`
- Add logic to get keys and names depending on `template` type
- Add validation for `template` type
- Modify `verify_newproject_script.yml` to be able to run CI successfully
- Modify `README.md` for the update
| xml | compose |
|--|--|
| ![xml](https://user-images.githubusercontent.com/32578035/203943843-5241473f-0c50-4468-921b-392a0f6dea58.png) | …
> [#336] [#338] Update new_project.kts to choose between XML or Compose and update documentation

- .cicdtemplate/.github/workflows/review_pull_request.yml
- .github/workflows/review_pull_request.yml
https://github.com/nimblehq/android-templates/issues/364
The CI failed on step `Set up Ruby` because the current action is `deprecated` and is `no longer maintained.`
We must migrate `action` from `actions/setup-ruby@v1` to `ruby/setup-ruby@v1`. For more info https://github.com/actions/setup-ruby
> [#364] Migrate workflows setup-ruby action

- sample-compose/app/src/main/AndroidManifest.xml
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/MainApplication.kt
- sample-xml/app/src/main/AndroidManifest.xml
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/MainApplication.kt
- scripts/new_project.kts
- template-compose/app/src/main/AndroidManifest.xml
- template-compose/app/src/main/java/co/nimblehq/template/compose/MainApplication.kt
- template-xml/app/src/main/AndroidManifest.xml
- template-xml/app/src/main/java/co/nimblehq/template/xml/MainApplication.kt
closes #361
- Removed `renameApplicationClass()`, `appNameWithoutSpace` and `applicationClassName` from new_project script
- Renamed all Application classes to `MainApplication`
| XML | Compose |
| --- | --- |
| <img width="414" alt="xml" src="https://user-images.githubusercontent.com/53168251/206683751-e7351da1-4e6a-4ac5-b343-4edcdc8adddd.png"> | <img width="430" alt="compose" src="https://user-images.githubusercontent.com/53168251/206683731-ea5112de-5580-490f-8747-eeac4875ace5.png"> |
> [#361] Update new_project.kts to keep application name as is

- sample-compose/detekt-config.yml
- sample-xml/detekt-config.yml
- template-compose/detekt-config.yml
- template-xml/detekt-config.yml
https://github.com/nimblehq/android-templates/issues/369
There is some `Detekt attrs` deprecated need to fix them.
- Update `attr` -> `threshold` to `functionThreshold` for `LongParameterList`.
- Update `attr` -> `ignoreOverriddenFunction` to `ignoreOverridden` for `MemberNameEqualsClassName`.
- Update `attr` -> `excludeAnnotatedProperties` to `ignoreAnnotated` for `LateinitUsage`.
- Update `attr` -> `excludeAnnotatedClasses` to `ignoreAnnotated` for `UseDataClass`.
- And for the left, we need to use `YAML array` instead of `comma-separated` string by following this pattern `[ '' ]`.
- We have updated `functionPattern` for `FunctionNaming` from ``^([a-z$][a-zA-Z$0-9]*)|(`.*`)$`` to `[a-zA-Z][a-zA-Z0-9]` to make it shorter.
- Add `UnusedPrivateMember` as we have this in …
> [#369] Update deprecated Detekt attrs in all templates

- sample-compose/app/build.gradle.kts
- sample-compose/app/src/main/AndroidManifest.xml
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
- sample-compose/buildSrc/src/main/java/Versions.kt
- template-compose/app/build.gradle.kts
- template-compose/buildSrc/src/main/java/Versions.kt
Solves https://github.com/nimblehq/android-templates/issues/370
- Migrating legacy permission requests on Fragment to the new approach in Jetpack Compose by removing `Peko` and switching to use https://google.github.io/accompanist/permissions/.
From what we have done in this PR https://github.com/nimblehq/android-templates/pull/324, we need to migrate all related `Peko` permission request stuff to [Accompanist permissions](https://google.github.io/accompanist/permissions) for Compose projects.
https://user-images.githubusercontent.com/16315358/207667660-4b3faebc-7cb9-4dc0-ab7e-441f879c028e.mp4
> [#370] [Compose] Migrate to the new permission request logic

- sample-compose/app/build.gradle.kts
- sample-compose/buildSrc/src/main/java/Versions.kt
- template-compose/app/build.gradle.kts
- template-compose/buildSrc/src/main/java/Versions.kt
https://github.com/nimblehq/android-templates/issues/373
After Google released [BOM](https://developer.android.com/jetpack/compose/setup#bom-version-mapping) for the compose libraries, it helps us to manage the latest versions of libraries we are using. Therefore, we don't need to handle it independently. However, if we want to fix version to some libraries, we can do it by [overriding the library version](https://developer.android.com/jetpack/compose/setup#how_do_i_use_a_different_library_version_than_whats_designated_in_the_bom).
Once we applied `BOM` we can get rid of the specifying version of these libs:
- `androidx.compose.ui:ui`
- `androidx.compose.ui:ui-tooling`
- `androidx.compose.foundation:foundation`
- `androidx.compose.material:material`
But, there're two libs that's relate …
> [#373] Update Compose dependecies using BOM version

- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/AppBar.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppColors.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppDimensions.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppShapes.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppStyles.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppTypography.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/Color.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/Dimension.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/Theme.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppColors.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppDimensions.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppShapes.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppStyles.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppTypography.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/Color.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/Dimension.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/Theme.kt
- template-compose/app/src/main/res/values/colors.xml
- template-compose/app/src/main/res/values/styles.xml
- Solves https://github.com/nimblehq/android-templates/issues/353
Set up base components for app resources and theme management for Compose template & sample.
- Get rid of using `object class` to define all necessary Color resources in the project. We will [define Color resources as top-level class `val` instead](https://github.com/nimblehq/android-templates/pull/376/files#diff-9bbe79848383e04fde7db80b8136a81e23c4f4cf55e295479cfd6a6b25101196). As discussed, we agreed that using [`object` is not optimized](https://nimble-co.slack.com/archives/G41UCTGHL/p1668064107638629?thread_ts=1668056608.803069&cid=G41UCTGHL).
- Create a new class `AppColors` to define app custom colors instead of having extensions on [Colors](https://github.com/nimblehq/android-templates/pull/376/files#diff-a306e2850925 …
> [#353] [Compose] Set up app resources and theme management

- sample-compose/app/src/main/java/co/nimblehq/sample/compose/model/UiModel.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/AppDestination.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/AppNavigation.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/ItemList.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/third/ThirdScreen.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/third/ThirdViewModel.kt
- sample-compose/app/src/main/res/values/strings.xml
- sample-compose/buildSrc/src/main/java/Versions.kt
- Closes #377 
Coming through [this discussion](https://github.com/nimblehq/android-templates/pull/372#discussion_r1058045844), we need to have a sample implementation to demonstrate how can we pass a parcelable data between destinations. Unfortunately, it's not that easy:
- https://betterprogramming.pub/realize-jetpack-compose-navigation-2889401f52b
- https://stackoverflow.com/questions/65610003/pass-parcelable-argument-with-compose-navigation
- https://stackoverflow.com/questions/67553012/passing-model-between-destinations/67553630#67553630
- https://gist.github.com/Aidanvii7/46f9f014ba4dc58a2ac10625b198769d
We should find an optimized way to apply it to the template.
- Tried to implement the way the links provided and I found [this …
> [#377] [Compose] Add a sample to navigate to the ThirdScreen with a custom parcelable data

- .github/workflows/bump_version.yml
Close https://github.com/nimblehq/android-templates/issues/394
Replace the version name of the variable instead of changing it directly in bundle files
- Replace `ANDROID_VERSION_NAME` variable with the new value, by using `Perl` command
https://github.com/nimblehq/android-templates/pull/402
> [#394] Fix bump version workflow

- sample-compose/app/build.gradle.kts
- sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
- sample-compose/app/src/test/resources/robolectric.properties
- sample-compose/buildSrc/src/main/java/Versions.kt
- template-compose/app/build.gradle.kts
- template-compose/app/src/androidTest/java/co/nimblehq/template/compose/ui/screens/home/HomeScreenTest.kt
- template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/home/HomeScreenTest.kt
- template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModelTest.kt
- template-compose/app/src/test/resources/robolectric.properties
- template-compose/buildSrc/src/main/java/Versions.kt
https://github.com/nimblehq/android-templates/issues/354
- Add a sample for writing UI test with Robolectric as unit test instead of an Instrument test.
- Set up running UI tests with Robolectric as default for the `template` project.
- Add `org.robolectric:robolectric` dependency in testImplementation.
- Add `androidx.compose.ui:ui-test-junit4` for Compose UI test and `androidx.test:rules` for permission granting.
- Clone `HomeScreenTest` from `androidTest` folder into `test` with replacing `@RunWith(AndroidJUnit4::class)` by `@RunWith(RobolectricTestRunner::class)`. Now our HomeScreenTest can run with Robolectric as unit test instead of an Instrument test ✅ 
All unit tests passed ✅ 
Kover now can report code coverage for `HomeScreen` ✅
> [#354] [Compose] 2/2: Add sample UI test with Robolectric

- sample-compose/app/build.gradle.kts
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
- sample-compose/buildSrc/src/main/java/Versions.kt
- template-compose/app/build.gradle.kts
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
- template-compose/buildSrc/src/main/java/Versions.kt
- Closes #410 
- Add dependency `androidx.lifecycle:lifecycle-runtime-compose` to use `collectAsStateWithLifeCycle()`
- Replace `collectAsState()` to `collectAsStateWithLifeCycle()` in `HomeScreen`
To use `androidx.lifecycle:lifecycle-runtime-compose` version `2.6.0-rc01`, we need to update the following libs versions:
- **androidx.lifecycle:lifecycle-runtime-ktx** from `2.5.1` to `2.6.0-rc01` to use the same version for lifecycle lib
- **kotlin version** from `1.7.20` to `1.8.10`
- **compose compiler version** from `1.3.2` to `1.4.3`
<details>
<summary>Template Compose</summary>
[template-compose.webm](https://user-images.githubusercontent.com/12026942/222374629-88186296-4d5e-44a8-8583-a5a8dfec7e29.webm)
</details>
<details>
<summary>Sample Compose</summary> …
> [#410] Update collectAsState to collectAsStateWithLifecyle for observing flow in Android lifecycle manner

- sample-compose/app/src/main/java/co/nimblehq/sample/compose/di/modules/PreferencesModule.kt
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/di/modules/PreferencesModule.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/PreferencesModule.kt
- template-xml/app/src/main/java/co/nimblehq/template/xml/di/modules/PreferencesModule.kt
- Closes #415 
Update dependency injection of DataStore to use builder pattern for sample-compose, sample-xml, template-xml and template-compose
Update providing DataStore dependency using [latest builder pattern](https://medium.com/androiddevelopers/datastore-and-dependency-injection-ea32b95704e3).
`PreferenceDataStoreFactory` accept 3 optional parameters and 1 mandatory parameter.
- `corruptionHandler` (optional) — invoked if a `CorruptionException` is thrown by the serializer when the data cannot be de-serialized which instructs DataStore how to replace the corrupted data
- `migrations` (optional) — a list of `DataMigration` for moving previous data into DataStore
- `scope` (optional) — the scope in which IO operations and transform functions will execute
- `produceFile` — generates …
> [#415] [Chore] Update dependency injection implementation for the DataStore from the delegate pattern to the builder pattern

- sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/extensions/ResponseMapping.kt
- sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/extensions/ResponseMapping.kt
- template-compose/data/src/main/java/co/nimblehq/template/compose/data/extensions/ResponseMapping.kt
- template-xml/data/src/main/java/co/nimblehq/template/xml/data/extensions/ResponseMapping.kt
Closes #426 
- Simple refactor from `try/catch` to `runCatching { ... }`
- Remove redundant annotation
All tests are successful and the app is still working correctly
> [#426] [Kotlin Flow] Refactor `try/catch` to `runCatching { ... }`

- .github/workflows/review_pull_request.yml
- .github/workflows/run_detekt_and_unit_tests.yml
- sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
Resolves https://github.com/nimblehq/android-templates/issues/443
- Add more steps to verify the `sample-xml` & `sample-compose` projects.
- Fix: missing UseCases setup & mocking in tests.
The number of steps in this workflow [run_detekt_and_unit_tests.yml](https://github.com/nimblehq/android-templates/blob/develop/.github/workflows/run_detekt_and_unit_tests.yml) is increased for 4 projects, we need to have some delimiters for better grouping.
The workflow [run_detekt_and_unit_tests.yml](https://github.com/nimblehq/android-templates/blob/develop/.github/workflows/run_detekt_and_unit_tests.yml) is passed ✅
> [#443] Fix: Missing additional use-cases mocking and tests verifying steps in CI for sample-xml & sample-compose

- sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/second/SecondViewModel.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/third/ThirdViewModel.kt
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/model/UiModel.kt
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/base/BaseViewModel.kt
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/MainViewModel.kt
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeViewModel.kt
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/second/SecondViewModel.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseViewModel.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModel.kt
- template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModelTest.kt
- template-xml/app/src/main/java/co/nimblehq/template/xml/model/UiModel.kt
- template-xml/app/src/main/java/co/nimblehq/template/xml/ui/base/BaseViewModel.kt
- template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/MainViewModel.kt
- template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/home/HomeViewModel.kt
https://github.com/nimblehq/android-templates/issues/425
- Use `launchIn` instead of `collect` for collecting Flows in ViewModel.
- Replace the old `execute` protected fun in BaseViewModel with the new `launch` fun (renaming for consistency).
- Add `injectLoading` fun to reduce the logic for `showLoading` and `hideLoading` at `onStart` and `onCompletion` in each Flow.
- The new `launch` fun should accept `EmptyCoroutineContext` as default ([same as the original fun](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/launch.html)). [With `EmptyCoroutineContext`, the `Dispatchers.Default` is used](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/launch.html) 👉 **main thread**, to launch the Job.
- [To launch a …
> [#425] [Kotlin Flow] Using "launchIn" instead of "collect" for collecting Flows in ViewModel

- sample-xml/app/src/main/java/co/nimblehq/sample/xml/extension/NavArgsExt.kt
- sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/second/SecondFragment.kt
- sample-xml/app/src/test/java/co/nimblehq/sample/xml/test/NavArgsExt.kt
- sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/home/HomeFragmentTest.kt
- sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/second/SecondFragmentTest.kt
- sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/xml/HomeFragmentTest.kt
- template-xml/app/src/main/java/co/nimblehq/template/xml/extension/NavArgsExt.kt
- template-xml/app/src/test/java/co/nimblehq/template/xml/test/NavArgsExt.kt
- template-xml/app/src/test/java/co/nimblehq/template/xml/ui/screens/home/HomeFragmentTest.kt
Close #299 
- Add UI test cases for `HomeFragment` and `SecondFragment`
- Create `provideNavArgs` extension function and integrate it in `SecondFragment`
- The `provideNavArgs` extension function mimics the behaviour of our `provideViewModel` so that we can easily mock the `navArgs` in the test
- Test case
- Code coverage
> [#299] [Sample] Add UI tests for XML sample code

- .github/wiki/Home.md
- .github/workflows/publish_docs_to_wiki.yml
- Closes #455 
As discussed in [this thread](https://nimble-co.slack.com/archives/CSQG2QXFX/p1680670636485339?thread_ts=1680669140.429079&cid=CSQG2QXFX):
- Added `Checkout the repository` step to our `publish-wiki-workflow`
- The Github wiki repo is using `master` branch by default (Check out [here](https://github.com/orgs/community/discussions/48537)), not `main` as our repository. So in this case, we need to push the wiki content to the `master` branch as the script does correctly. ✅ 
After running the workflow with additional steps, Wiki page has been updated:
> [#455] Add checkout repository step to the workflow

- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/test/CoroutineTestRule.kt
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/BaseScreenTest.kt
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
- sample-compose/buildSrc/src/main/java/Versions.kt
- sample-compose/data/build.gradle.kts
- template-compose/app/src/test/java/co/nimblehq/template/compose/test/CoroutineTestRule.kt
- template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/BaseScreenTest.kt
- template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/home/HomeScreenTest.kt
- template-compose/buildSrc/src/main/java/Versions.kt
- template-compose/data/build.gradle.kts
https://github.com/nimblehq/android-templates/issues/465
- Research & find a valid way to [test SharedFlow execution in Composable with Robolectric without converting it to StateFlow](https://github.com/nimblehq/android-templates/pull/399/commits/60e64877ad732f5daef82e5bda19320fca75aad2). 
- Apply using `viewModel.error.collectAsEffect` for error handling.
- Define a `BaseScreenTest` as a helper to simplify the test logic for Compose.
- Update Compose & testing dependencies to latest versions 🚀 
- To assert a Toast from a SharedFlow execution in the ViewModel's `init` block with Robolectric, 
- set [`coroutinesRule.testDispatcher = StandardTestDispatcher()`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-standard-test-dispatcher.html)
- use …
> [#465] [Compose] Optimize to test "SharedFlow" execution in Composable with Robolectric

- scripts/new_project.kts
closes #437 
- Added `isError` argument to `showMessage()`
- Added ❌ to the beginning of error messages
We could manually add the cross to each error message, but that means we need to add it to any new error messages we may have which seems less maintainable 🤔 
<br/>
<br/>
> [#437] Add red cross emoji to error messages when new_project.kts fails 

- sample-compose/build.gradle.kts
- template-compose/build.gradle.kts
https://github.com/nimblehq/android-templates/issues/464
Update Kover's exclusion config to 
- remove legacy XML method component exclusion config:
- Redundant ViewBinding or DataBinding.
- Redundant XML method components, e.g., Adapter, Dagger's generated code for XML.
- Redundant Navigation Component.
- exclude Jetpack Compose generate code:
- ComposableSingletons.
- Previews.
It's not so clear to separate between `package` & `file` exclusion config now. We can just combine all into `excludedFiles`.
Updated Kover's code coverage report ✅
> [#464] [Compose] Update Kover's exclusion config

- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/AppBar.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/ItemList.kt
https://github.com/nimblehq/android-templates/issues/428
- We do not need to add this to `Preview` composables.
Currently, we don't have a `subcomponent` of `composables` in `template-compose`. Therefore, we will update only in `sample-compose`.
N/A
> [#428] [Chore] Update composables to have a Modifier parameter with default value

- README.md
- scripts/new_project.kts
closes #433
- Added `force` argument to `new_project` script
- Added `exitWithError` method to handle generated project deletion
- Updated `README` with new `force` argument
We should make sure that `projectFolderName` isn't empty (such as when `package-name` or `app-name` isn't valid), otherwise we could end up deleting the root folder instead 🙈 
`force=false`:
https://github.com/nimblehq/android-templates/assets/53168251/136d66ae-5968-4f88-9978-cef802faa83c
`force=true`:
https://github.com/nimblehq/android-templates/assets/53168251/b429d299-8b23-4a80-a693-2dd5f9b7f38c
> [#433] Remove new project folder if `new_project.kts` fails

- sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
- sample-compose/app/src/main/res/values/strings.xml
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
- sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
https://github.com/nimblehq/android-templates/issues/419
When the app is launched for the first time, we show a toast saying "This is the first time launch". After navigating to the second screen by clicking an item on the list and then navigating back to home, the toast reappears.
Expected behavior: show the toast message only once on the Home screen when the app is launched for the first time.
* The `isFirstTimeLaunch` `StateFlow` is being observed from `HomeScreen`. `isFirstTimeLaunch` is updated only once when initializing the VM. So everytime the user navigates back from the second screen, the initial value `true` is observed by `HomeScreen` resulting in the bug.
* Fixed the issue by updating the `SharedPreferences` value as well as `isFirstTimeLaunch` only _after_ the toast is shown …
> [#419] [Bug] Prevent the toast for first time app launch from reappearing after navigating back from the second screen

- README.md
- scripts/new_project.kts
https://github.com/nimblehq/android-templates/issues/436
* Add an argument destination that accepts a path to the generated project location
If no argument is given, default to the template root folder.
* `destination` must accept both absolute (`/Users/johndoe/documents/projectfolder`) and relative paths (`../projectfolder`).
* Added the argument.
* We only validate if the supplied argument is blank and show an error if that's the case. For any invalid path, the execution will fail on its own.
https://github.com/nimblehq/android-templates/assets/8093908/a01f9b0d-9374-4122-b851-eafe2d642928
> [#436] Add an argument to specify output folder location to new_project.kts script

- RxJavaTemplate[DEPRECATED]/build.gradle.kts
- sample-compose/build.gradle.kts
- sample-xml/build.gradle.kts
- template-compose/build.gradle.kts
- template-xml/build.gradle.kts
- Close https://github.com/nimblehq/android-templates/issues/485
- Update the maven import to be in Kotlin format
Ref: https://stackoverflow.com/a/66926254/11393626
The CI should be successful.
> [#485] Fix repositories import syntax to be in Kotlin format for maven Jitpack

- README.md
- Closes https://github.com/nimblehq/android-templates/issues/454
Update code block script from double backticks code (``) to the [Fenced Code Block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks)
N/A
> [#454] Update generating project example script to be in Fenced Code Block

- RxJavaTemplate[DEPRECATED]/build.gradle.kts
- sample-compose/build.gradle.kts
- sample-xml/build.gradle.kts
- template-compose/build.gradle.kts
- template-xml/build.gradle.kts
- Closes https://github.com/nimblehq/android-templates/issues/485
- Update import libraries from MavenCentral at a higher priority than Jitpack.
As Chucker recommended to be imported from MavenCentral instead Jitpack, so we should follow the instruction.
The CI should be all green.
> [#485] Update import libraries from mavenCentral if possible

- .cicdtemplate/.codemagic/codemagic.yaml
- .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
- .cicdtemplate/.github/workflows/review_pull_request.yml
- .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
- .github/workflows/review_pull_request.yml
- .github/workflows/run_detekt_and_unit_tests.yml
- codemagic.yaml
- template-compose/app/build.gradle.kts
- template-compose/build.gradle.kts
- template-compose/buildSrc/src/main/java/Versions.kt
- Close https://github.com/nimblehq/android-templates/issues/496
Remove Firebase integration from project
- Codemagic can distribute the app to Firebase App Distribution without integrating the Firebase to the project.
- After merging this PR, the `google-services.json` in Github Secrets will be deleted.
Big thanks to @luongvo for noticing this and the POC branch. 🙇🏻‍♀️ 
Github Action to deploy on Firebase result:
https://github.com/nimblehq/android-templates/actions/runs/5712267786/job/15475425029
Codemagic to deploy on Firebase result:
> [#496] Distribute app without Firebase integration

- .cicdtemplate/.github/workflows/bump_version.yml
- .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
- .cicdtemplate/.github/workflows/review_pull_request.yml
- .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
- .github/workflows/bump_version.yml
- .github/workflows/draft-new-release.yml
- .github/workflows/publish_docs_to_wiki.yml
- .github/workflows/review_pull_request.yml
- .github/workflows/run_detekt_and_unit_tests.yml
- .github/workflows/verify_newproject_script.yml
closes #500
- Removed the token from Bump Version checkout step
- Updated all Checkout calls for consistency
We call the Checkout action on every workflow but the step name and version are inconsistent, so they have been updated in this PR too 👀 
[Workflow run](https://github.com/nimblehq/android-templates/actions/runs/6427439143)
[Bump version PR](https://github.com/nimblehq/android-templates/pull/534)
> [#500] The "Checkout" step in "bump_version" workflow does not need to set a custom token 

- .cicdtemplate/.github/workflows/bump_version.yml
closes #521
Replaced the `android-version-action` in `.cicdtemplate/.github/workflows/bump_version.yml` with the Perl command from `.github/workflows/bump_version.yml`
N/A
[Generated project PR](https://github.com/ryan-conway/test-bump-version/pull/1)
[Generated project workflow run](https://github.com/ryan-conway/test-bump-version/actions/runs/6429079443)
> [#521] Fix: The bump_version template workflow does NOT work

- .github/workflows/bump_version.yml
closes #502 
- Removed the `Bump version XML` from `bump_version` workflow
The XML template is being deprecated so we should no longer bump the version on new iterations 🙏🏻 
[Pull Request](https://github.com/nimblehq/android-templates/pull/526)
[Workflow run](https://github.com/nimblehq/android-templates/actions/runs/6416836897)
> [#502] Remove Bump version XML step from Bump version workflow

- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppDimensions.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppDimensions.kt
https://github.com/nimblehq/android-templates/issues/543
We're adopting a new approach. The medium space is defined as 16.dp, with a spacing step of 4.dp. This simplifies both memorization and reference.
```
val spacing2XSmall = 4.dp
val spacingXSmall = 8.dp
val spacingSmall = 12.dp
val spacingMedium = 16.dp
val spacingLarge = 20.dp
val spacingXLarge = 24.dp
val spacing2XLarge = 28.dp
val spacing3XLarge = 32.dp
```
- Add default spacing definition in `template-compose` and `sample-compose`
N/A
> [#543] Add default spacing definition in app dimensions

- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseViewModel.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModel.kt
- Closes #535 
Currently we can emit values to our `StateFlow` variables by casting them to `MutableStateFlow`. We should update our `StateFlow` declarations to make them read-only
- Update our `StateFlow` declarations as follows:
```
private val _uiModels = MutableStateFlow<List<UiModel>>(emptyList())
val uiModels = _uiModels.asStateFlow()
```
- Apply updates to `template-compose` and `sample-compose` ViewModels
The application still runs as usual.
https://github.com/nimblehq/android-templates/assets/32578035/5777eb87-1f95-4d24-a5a5-658e47276247
> [#535] Add asStateFlow to the StateFlow variables in ViewModel class

- .cicdtemplate/.github/workflows/bump_version.yml
- .cicdtemplate/.github/workflows/review_pull_request.yml
- .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
- .github/workflows/bump_version.yml
- .github/workflows/draft-new-release.yml
- .github/workflows/review_pull_request.yml
- .github/workflows/run_detekt_and_unit_tests.yml
- .github/workflows/verify_newproject_script.yml
- Closes #462 
The [cancel-workflow action added a warning on their README](https://github.com/styfle/cancel-workflow-action) that GitHub now supports concurrency and this workflow might not be needed anymore.
Resource: https://docs.github.com/en/actions/using-jobs/using-concurrency
Sample implementation: https://github.com/nimblehq/rails-templates/pull/398 
Add concurrency for all workflows except the following 2:
- `.github/workflows/publish_docs_to_wiki`
- `.cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml`
> [#462] Update GitHub workflows to use concurrency

- scripts/new_project.kts
https://github.com/nimblehq/android-templates/issues/509
Add `--stacktrace` parameter when executing the commands.
The error in the PoW occurs when building the project fails.
> [#509] [Script] Add --stacktrace parameter in the command executions to provide a full stack trace for debugging

- sample-compose/app/src/main/AndroidManifest.xml
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/AppDestination.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/AppNavGraph.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/AppDestination.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/AppNavGraph.kt
Closes https://github.com/nimblehq/android-templates/issues/548
- Define a new `deeplinks` attribute in AppDestination to config deeplink.
- Add a deeplink sample with 
- web links `https://android.nimblehq.co/`
- custom scheme links `android://`
- Follow this simple guide https://developer.android.com/jetpack/compose/navigation#deeplinks
- To set up app links, follow https://developer.android.com/studio/write/app-link-indexing. We must request to upload the generated `assetlinks.json` to the host, e.g., https://android.nimblehq.co/.well-known/assetlinks.json.
- Defining `NavDeepLink` with Uri (Android resources) in `AppDestination` caused the unit tests to fail. We must move NavDeepLink from `AppDestination` to `NavGraphBuilder.composable`.
We can use this tool for testing besides the …
> [#548] Prepare initial setup for deep-link

- .cicdtemplate/.codemagic/codemagic.yaml
- codemagic.yaml
- Closes #490 
Add command line script to get the commit message to show as the release note on Codemagic CD workflow
- For Staging, we use the latest merge commit message
- For Production, we use the latest 50 merge commit messages from the last tag. 
Staging:
> [!NOTE]
> We need to merge this change to `main` first to see the release note on the Firebase App Distribution.
> But as I test the script, it works correctly in the following image:
> [#490] Add release note for Codemagic CD workflow

- sample-compose/app/build.gradle.kts
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseScreen.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/main/home/HomeScreen.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/main/second/SecondScreen.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/main/third/ThirdScreen.kt
- sample-compose/app/src/main/java/co/nimblehq/sample/compose/util/ComposableUtil.kt
- sample-compose/app/src/main/res/values/colors.xml
- sample-compose/app/src/main/res/values/styles.xml
- sample-compose/buildSrc/src/main/java/Versions.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseScreen.kt
- template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/main/home/HomeScreen.kt
Closes https://github.com/nimblehq/android-templates/issues/553
- Create a `BaseScreen` composable for all screens, as we did with `BaseActivity` or `BaseFragment`.
- Add `accompanist-systemuicontroller` to demo the status bar color changing between screens.
The `BaseScreen` will contain base parameters to request & base logic in the body to execute for all screens.
```
@Composable
fun BaseScreen(
// TODO Base parameters to request on all screens here
content: @Composable () -> Unit,
) {
// TODO Base logic for all screens here
content()
}
```
https://github.com/nimblehq/android-templates/assets/16315358/4de60402-020a-4eb5-ab22-e3963693cebc
> [#553] Define BaseScreen composable for all screens

- template-compose/app/build.gradle.kts
- template-compose/buildSrc/src/main/java/Dependencies.kt
https://github.com/nimblehq/android-templates/issues/580
Hide Compose `androidx.compose.ui.tooling.PreviewActivity` from the final release build.
According to the latest update https://developer.android.com/develop/ui/compose/tooling:
- `ui-tooling-preview`: Contains the API definitions
- `ui-tooling`: Contains the implementation and can be declared as debugImplementation
No more `Activity (androidx.compose.ui.tooling.PreviewActivity) is not Protected. [android:exported=true]` issue from the new VAPT report ✅
| Before | After |
|--------|--------|
| ![Screenshot 2024-07-18 at 12 01 46](https://github.com/user-attachments/assets/ca12bfe2-e7d1-4fe4-a672-86e3aad83181) | ![Screenshot 2024-07-18 at 12 37 49](https://github.com/user-attachments/assets/d94e4bef-1697-4094-8a7c-95c4aa50004e) |
> [#580] Hide Compose androidx.compose.ui.tooling.PreviewActivity from the final release build
